image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk add --update --no-cache git

pages:
  script:
  - hugo 
  artifacts:
    paths:
    - public
  only:
  - main